// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartTutor.ContentModel;

namespace SmartTutor.Migrations
{
    [DbContext(typeof(SmartTutorContext))]
    [Migration("20201112141819_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SmartTutor.ContentModel.EducationalContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ContentDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("ContentQuality")
                        .HasColumnType("integer");

                    b.Property<List<int>>("EducationSnippetsIds")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("EducationalContents");
                });

            modelBuilder.Entity("SmartTutor.ContentModel.EducationalSnippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int?>("EducationalContentId")
                        .HasColumnType("integer");

                    b.Property<int>("SnippetDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("SnippetQuality")
                        .HasColumnType("integer");

                    b.Property<int>("SnippetType")
                        .HasColumnType("integer");

                    b.Property<List<Tag>>("Tags")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("EducationalContentId");

                    b.ToTable("EducationalSnippets");
                });

            modelBuilder.Entity("SmartTutor.ContentModel.EducationalSnippet", b =>
                {
                    b.HasOne("SmartTutor.ContentModel.EducationalContent", null)
                        .WithMany("EducationSnippets")
                        .HasForeignKey("EducationalContentId");
                });
#pragma warning restore 612, 618
        }
    }
}
